
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

package org.rafaelsolis.analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PYCOMA = 3;
  public static final int CONCATENACION = 7;
  public static final int CONJUNTO = 14;
  public static final int RCONJ = 2;
  public static final int LLAVEC = 6;
  public static final int LLAVEA = 5;
  public static final int ID = 12;
  public static final int CANULABLE = 11;
  public static final int SEPARADOR = 15;
  public static final int ASIGNACION = 13;
  public static final int COMENT_MLINEA = 16;
  public static final int COMENT_ULINEA = 17;
  public static final int EOF = 0;
  public static final int CADENA_COMILLAS = 18;
  public static final int CKLEENE = 9;
  public static final int DISYUNCION = 8;
  public static final int error = 1;
  public static final int DPUNTOS = 4;
  public static final int CPOSITIVA = 10;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "RCONJ",
  "PYCOMA",
  "DPUNTOS",
  "LLAVEA",
  "LLAVEC",
  "CONCATENACION",
  "DISYUNCION",
  "CKLEENE",
  "CPOSITIVA",
  "CANULABLE",
  "ID",
  "ASIGNACION",
  "CONJUNTO",
  "SEPARADOR",
  "COMENT_MLINEA",
  "COMENT_ULINEA",
  "CADENA_COMILLAS"
  };
}

